import { useState, useEffect } from 'react';

const loveReasons = [
  "The way you scrunch your nose when you laugh",
  "Your kindness to everyone you meet",
  "How you make everything an adventure",
  "Your beautiful, genuine smile",
  "The way you listen with your whole heart",
  "Your incredible sense of humor",
  "How you see the good in everyone",
  "Your adorable sleepy voice in the morning",
  "The way you dance when you think no one's watching",
  "Your endless curiosity about the world",
  "How you remember the little things I tell you",
  "Your amazing cooking skills",
  "The way you light up when talking about your passions",
  "Your beautiful, expressive eyes",
  "How you make me laugh until my stomach hurts",
  "Your incredible strength and resilience",
  "The way you hum while doing chores",
  "Your love for animals and nature",
  "How you make even mundane tasks fun",
  "Your thoughtful texts throughout the day",
  "The way you get excited about small surprises",
  "Your beautiful handwriting",
  "How you always smell amazing",
  "Your infectious enthusiasm",
  "The way you comfort me when I'm stressed",
  "Your amazing fashion sense",
  "How you make me want to be a better person",
  "Your cute little snores",
  "The way you celebrate my victories",
  "Your incredible patience with me",
  "How you always know what to say",
  "Your love for learning new things",
  "The way you make ordinary moments special",
  "Your beautiful laugh that fills the room",
  "How you remember my favorite things",
  "Your amazing hugs that feel like home",
  "The way you encourage my dreams",
  "Your love for cozy movie nights",
  "How you make me feel safe and loved",
  "Your beautiful soul that shines so bright",
  "The way you play with your hair when thinking",
  "Your incredible empathy and compassion",
  "How you make me believe in forever",
  "Your cute reactions to funny videos",
  "The way you support all my silly ideas",
  "Your beautiful singing voice in the shower",
  "How you make me feel like the luckiest person alive",
  "Your love for spontaneous adventures",
  "The way you make every day better just by being in it",
  "Your incredible inner beauty that radiates outward",
  "How you make love feel effortless and natural",
  "Your adorable bedhead in the mornings",
  "The way you get passionate about things you care about",
  "Your amazing ability to make me smile",
  "How you turn my house into a home",
  "Your beautiful freckles that I could count forever",
  "The way you make me feel understood",
  "Your love for trying new foods together",
  "How you make me laugh at the worst jokes",
  "Your incredible work ethic and determination",
  "The way you make me feel cherished every day",
  "Your cute habit of talking to yourself",
  "How you make my heart skip a beat",
  "Your amazing ability to multitask",
  "The way you make me feel like I can conquer the world",
  "Your love for cozy blankets and warm drinks",
  "How you make every season feel special",
  "Your incredible memory for important dates",
  "The way you make me want to write poetry",
  "Your beautiful spirit that lifts everyone up",
  "How you make me believe in magic again",
  "Your cute excited face when you see dogs",
  "The way you make me feel grateful every day",
  "Your amazing ability to find beauty everywhere",
  "How you make me a better version of myself",
  "Your incredible talent for making me feel loved",
  "The way you make time stop when you look at me",
  "Your love for deep conversations under the stars",
  "How you make me understand what home really means",
  "Your beautiful heart that chose to love mine",
  "The way you make me excited about our future together",
  "Your incredible ability to turn any day around",
  "How you make me believe in happily ever after",
  "Your cute concentrated face when you're focused",
  "The way you make me want to be the best partner",
  "Your amazing grace in handling life's challenges",
  "How you make me understand what true love really is",
  "Your beautiful presence that makes everything better",
  "The way you make me grateful to be alive",
  "Your incredible heart that beats for both of us",
  "How you make me believe we can weather any storm",
  "Your beautiful soul that found its way to mine",
  "The way you make me want to love you forever",
  "Your incredible ability to make me feel complete",
  "How you make me understand why it never worked with anyone else",
  "Your beautiful love that changed my entire world",
  "The way you make me excited to wake up each morning",
  "Your incredible presence that feels like coming home",
  "How you make me believe in us more every single day",
  "Your beautiful existence that makes my life worth living",
  "The way you love me exactly as I am",
  "Your incredible heart that beats in perfect rhythm with mine",
  "How you make me understand what forever really means",
  "Your beautiful love that is my greatest treasure",
  "The way you make me feel like I'm floating on air",
  "Your adorable nose crinkle when you're confused",
  "How you make grocery shopping feel like a date",
  "Your incredible ability to make me feel chosen",
  "The way you steal my hoodies and look better in them",
  "Your beautiful morning voice that I want to wake up to forever",
  "How you make me laugh when I want to cry",
  "Your amazing talent for finding the perfect words",
  "The way you make me feel like I'm your whole world",
  "Your incredible strength during difficult times",
  "How you make me want to be worthy of your love",
  "Your beautiful way of seeing the world",
  "The way you make me believe in second chances",
  "Your amazing ability to light up any room",
  "How you make me feel like the main character in my own life",
  "Your incredible kindness to strangers",
  "The way you make me want to give you everything",
  "Your beautiful laugh that I could listen to forever",
  "How you make me understand what partnership really means",
  "Your amazing ability to make me feel safe",
  "The way you make me believe in the power of love",
  "Your incredible patience with my bad jokes",
  "How you make me feel like I've finally found my person",
  "Your beautiful way of caring for others",
  "The way you make me want to be better every day",
  "Your amazing ability to turn ordinary moments into memories",
  "How you make me feel like we're in our own little world",
  "Your incredible talent for making me feel special",
  "The way you make me believe dreams can come true",
  "Your beautiful heart that loves so generously",
  "How you make me understand what it means to be truly seen",
  "Your amazing ability to make me feel understood",
  "The way you make me excited about growing old together",
  "Your incredible strength in vulnerability",
  "How you make me feel like I'm exactly where I belong",
  "Your beautiful way of loving without conditions",
  "The way you make me want to protect your heart",
  "Your amazing ability to make me feel like I matter",
  "How you make me believe in the beauty of commitment",
  "Your incredible talent for making me smile on hard days",
  "The way you make me feel like we're writing our own fairy tale",
  "Your beautiful presence that calms every storm in my heart",
  "How you make me understand what it means to choose someone every day",
  "Your amazing ability to make me feel like I'm enough",
  "The way you make me believe in the magic of everyday moments",
  "Your incredible heart that sees the best in everything",
  "How you make me feel like love is an adventure worth taking",
  "Your beautiful soul that makes me want to be a better human",
  "The way you make me understand what 'forever' really means",
  "Your amazing ability to make me feel like I'm home wherever you are",
  "How you make me believe that some people are just meant to find each other",
  "Your incredible way of loving that makes me feel invincible",
  "The way you make me want to love you better every single day",
  "Your beautiful heart that beats in harmony with mine",
  "How you make me understand that this is what I've been searching for my whole life",
  "Your amazing ability to make me feel like we're infinite",
  "The way you make me believe in the kind of love that moves mountains",
  "Your incredible presence that turns every day into a celebration",
  "How you make me feel like I've won the lottery of love",
  "Your beautiful way of making me feel like I'm the only person in the world",
  "The way you make me understand what it means to love someone more than yourself",
  "Your amazing ability to make me feel like we're creating something beautiful together",
  "How you make me believe that fairy tales do exist, and we're living one",
  "Your incredible heart that chose mine out of all the hearts in the world",
  "The way you make me feel like every day is Valentine's Day",
  "Your beautiful love that makes me want to be the best version of myself",
  "How you make me understand what it means to find your soulmate",
  "Your amazing ability to make me feel like we're meant to be",
  "The way you make me believe in the power of two hearts becoming one",
  "Your incredible presence that makes every moment feel precious",
  "How you make me feel like I want to spend every lifetime with you",
  "Your beautiful soul that recognizes mine",
  "The way you make me understand what home feels like",
  "Your amazing ability to make me feel completely loved",
  "How you make me believe that this is what 'the one' feels like",
  "Your incredible heart that loves me even on my worst days",
  "The way you make me feel like we're writing the most beautiful love story",
  "Your beautiful presence that makes me grateful for every breath",
  "How you make me understand what it means to love unconditionally",
  "Your amazing ability to make me feel like I'm exactly who I'm supposed to be with you",
  "The way you make me believe in the magic of finding your person",
  "Your incredible love that makes me want to give you the world",
  "How you make me feel like every love song was written about us",
  "Your beautiful heart that makes me want to be worthy of your love",
  "The way you make me understand what it means to be truly, deeply happy",
  "Your amazing ability to make me feel like we're creating our own little universe",
  "How you make me believe that some love stories are just meant to be epic",
  "Your incredible presence that makes me feel like I'm living in a dream",
  "The way you make me feel like you're my greatest adventure and my safest harbor",
  "Your beautiful soul that makes me want to love you in ways I never knew existed",
  "How you make me understand that this is what people mean when they talk about 'forever love'",
  "Your amazing ability to make me feel like we're two halves of the same heart",
  "The way you make me believe that destiny is real, and you're mine",
  "Your incredible heart that makes me want to spend every second loving you",
  "How you make me feel like every day with you is a gift I get to unwrap",
  "Your beautiful love that makes me understand why it never worked with anyone else",
  "The way you make me feel like we're creating something that will last lifetimes",
  "Your amazing ability to make me believe in the kind of love that poets write about",
  "How you make me understand what it means to love someone with your entire existence",
  "Your incredible presence that makes me feel like I'm exactly where I've always belonged",
  "The way you make me feel like our love story is just beginning",
  "Your beautiful heart that makes me want to love you more perfectly every day",
  "How you make me believe that this is what happily ever after actually looks like",
  "Your amazing ability to make me feel like we're meant to love each other forever",
  "The way you make me understand that you're not just my love, you're my home",
  "Your incredible soul that makes me want to choose you in every lifetime",
  "How you make me feel like together we can create something beautiful and eternal",
  "Your beautiful love that makes me believe in the magic of soulmates",
  "The way you make me feel like you're my person, my forever, my everything",
  "Your amazing heart that makes me want to love you with everything I have",
  "How you make me understand that this is what it feels like to find your other half",
  "Your incredible presence that makes me feel like we're infinite",
  "The way you make me believe that our love is the kind that legends are made of",
  "Your beautiful soul that makes me want to spend forever getting to know you",
  "How you make me feel like every moment with you is a moment I want to live forever",
  "Your amazing love that makes me understand what it means to be completely, utterly yours",
  "The way you make me feel like we're writing a love story that will inspire others",
  "Your incredible heart that makes me want to love you better than anyone has ever been loved",
  "How you make me believe that this is what it feels like when the universe conspires to bring two people together",
  "Your beautiful presence that makes me feel like I want to love you for all eternity",
  "The way you make me understand that you're not just my girlfriend, you're my destiny",
  "Your amazing ability to make me feel like our love is the most beautiful thing in existence",
  "How you make me believe that this is what it feels like to find your forever person",
  "Your incredible soul that makes me want to love you in this life and every life after",
  "The way you make me feel like together we're creating something magical and eternal",
  "Your beautiful heart that makes me understand what it means to love someone completely",
  "How you make me feel like you're my favorite person to love and my favorite person to be loved by",
  "Your amazing love that makes me believe we're meant to spend forever together",
  "The way you make me understand that this is what true love feels like",
  "Your incredible presence that makes me feel like loving you is the best thing I'll ever do",
  "How you make me believe that our hearts were made to beat as one",
  "Your beautiful soul that makes me want to give you a love that's worthy of who you are",
  "The way you make me feel like we're not just in love, we're home",
  "Your amazing heart that makes me understand why they call it 'falling' in love - because with you, I never want to stop falling",
  "How you make me believe that this is what it feels like to love someone with your whole soul",
  "Your incredible love that makes me feel like we're creating our own definition of forever",
  "The way you make me understand that you're my greatest love and my deepest joy",
  "Your beautiful presence that makes me feel like I want to love you until the end of time and beyond",
  "How you make me believe that we're not just lovers, we're two souls who found their way back to each other",
  "Your amazing ability to make me feel like our love is the kind that transcends everything",
  "The way you make me understand that loving you is both my greatest privilege and my deepest honor",
  "Your incredible heart that makes me want to spend every heartbeat loving you",
  "How you make me feel like we're writing a love story that will echo through eternity",
  "Your beautiful soul that makes me believe that this is what it feels like to love someone with infinite depth",
  "The way you make me understand that you're my heart's truest home",
  "Your amazing love that makes me feel like we're meant to love each other in ways that redefine what love means",
  "How you make me believe that this is what it feels like when two hearts become one",
  "Your incredible presence that makes me want to love you with a love that's as endless as you are beautiful",
  "The way you make me feel like our love is both my anchor and my wings",
  "Your beautiful heart that makes me understand that loving you is the most natural thing in the world",
  "How you make me believe that we're creating a love that will be remembered long after we're gone",
  "Your amazing soul that makes me want to love you with every fiber of my being",
  "The way you make me feel like together we're writing the most beautiful love letter to the universe",
  "Your incredible love that makes me understand that this is what it means to find your person",
  "How you make me believe that our love story is just the beginning of forever",
  "Your beautiful presence that makes me want to love you in ways that words can't express",
  "The way you make me feel like loving you is both my greatest adventure and my safest harbor",
  "Your amazing heart that makes me understand that this is what it feels like to love and be loved perfectly",
  "How you make me believe that we're not just meant to be together, we're meant to love each other infinitely",
  "Your incredible soul that makes me want to spend forever showing you how deeply you're loved",
  "The way you make me feel like our love is the most beautiful miracle I've ever witnessed",
  "Your beautiful love that makes me understand that this is what it feels like to find your forever",
  "How you make me believe that loving you is the best decision I'll ever make",
  "Your amazing presence that makes me want to love you with a love that grows stronger every day",
  "The way you make me feel like we're creating something that will last beyond time itself",
  "Your incredible heart that makes me understand that you're my greatest blessing and my deepest love",
  "How you make me believe that this is what it feels like when the universe gives you exactly what your heart has been searching for",
  "Your beautiful soul that makes me want to love you with every breath I take",
  "The way you make me feel like our love is both my greatest treasure and my most precious gift",
  "Your amazing love that makes me understand that this is what it means to be completely, utterly, and forever yours"
];

const InfiniteReasons = () => {
  const [displayedReasons, setDisplayedReasons] = useState<string[]>([]);
  const [currentIndex, setCurrentIndex] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      if (currentIndex < loveReasons.length) {
        setDisplayedReasons(prev => [...prev, loveReasons[currentIndex]]);
        setCurrentIndex(prev => prev + 1);
      } else {
        // Reset and start over
        setCurrentIndex(0);
        setDisplayedReasons([]);
      }
    }, 3000);

    return () => clearInterval(interval);
  }, [currentIndex]);

  return (
    <div className="bg-sage-green/30 p-8 rounded-3xl shadow-soft border border-sage-green/50">
      <h2 className="font-romantic text-4xl text-foreground mb-8 text-center">
        Reasons why I love YOU:
      </h2>
      
      <div className="space-y-4 max-h-96 overflow-y-auto pr-4">
        {displayedReasons.map((reason, index) => (
          <div
            key={index}
            className="bg-cream/80 p-4 rounded-xl shadow-soft border border-love-pink/30 fade-in"
            style={{ animationDelay: `${index * 0.1}s` }}
          >
            <div className="flex items-start gap-3">
              <span className="text-heart-red text-xl">♥</span>
              <p className="font-body text-foreground">{reason}</p>
            </div>
          </div>
        ))}
        
        {displayedReasons.length === 0 && (
          <div className="text-center py-8">
            <p className="font-romantic text-xl text-muted-foreground">
              Getting ready to share all the reasons I love you... 💕
            </p>
          </div>
        )}
      </div>
      
      <div className="text-center mt-6">
        <p className="font-body text-sm text-muted-foreground">
          {displayedReasons.length} of {loveReasons.length} reasons shared so far...
        </p>
      </div>
    </div>
  );
};

export default InfiniteReasons;